name: storage
description: In-memory stores and the Store<T> interface. Change-based updates, change-number tracking.

# TODO: remove once ready to publish to pub.dev
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.0.0

dependencies:
  models:
    path: ../models

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
